# Generated by Django 3.2.23 on 2024-01-05 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20240105_1238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='order_line',
        ),
    ]
