# Generated by Django 3.2.23 on 2024-01-08 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_has_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total_purchased',
            field=models.IntegerField(default=0),
        ),
    ]
